### ISSUE TITLE
Some questions about the dataset

### ISSUE THREAD

**Issue by longqianh** [yanlongbinluck/C2H-data#2]
Hello! I want to cite your dataset in a recent work, but there are some questions about it:

1. In your paper regarding this dataset, the dataset was described as 128 channels, but here were only 30 channels, did you do downsampling? Are the original 128-channel data available?
2. What does the channel range? For example, like the ICVL dataset that has 31 channels ranging from 400 to 700nm with 10nm interval.
3. I was wondering if you could provide the parser (maybe a python file) of the `xml` files in your dataset.

I would really appreciate it if you could help me with these questions.

**Comment by yanlongbinluck** [comment]
Hi,
1. We have added the link of raw 128-channel hyperspectral images data in the readme.
2. For channel range, we have declared it in our paper. Please see IV section of our paper. For 128-channel data, it 400-1000 nm with a spectral resolution of  0.58 nm. For 30-channel data, it 450–740 nm with 10 nm spectral resolution.
3. It is easy to find code snippet to parser the xml file. Using xml package.

**Comment by longqianh** [comment]
Thanks for the kind reply! Very sorry for the omission of the IV section🥺
